GET http://localhost:3000/api/v1/tasks HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmU3NzgzODhhNGM3MDc3NDA1MDFlMiIsImlhdCI6MTYyMzA5NjI0OCwiZXhwIjoxNjI1Njg4MjQ4fQ.BMnuN9XtYjcu6VdDBfgW59ek9RdWuWIZr_3Ii7GAYuI